#!/usr/bin/env bash

NAME=$(basename $0)
SCRIPT=$(readlink -f $0)
SCRIPT_DIR=$(dirname $SCRIPT)

LS_COMMAND=$(which ls)
PS_COMMAND=$(which ps)
TR_COMMAND=$(which tr)
WC_COMMAND=$(which wc)
CAT_COMMAND=$(which cat)
AWK_COMMAND=$(which awk)
SED_COMMAND=$(which sed)
TAR_COMMAND=$(which tar)
GREP_COMMAND=$(which grep)
WGET_COMMAND=$(which wget)
UNAME_COMMAND=$(which uname)
APT_GET_COMMAND=$(which apt-get)

OS=$($UNAME_COMMAND -o)
AUTHOR="Artem Teleshev <artem.teleshev@gmail.com>"
VERSION="1.0"

SCRIPT_DIR_ETC=$SCRIPT_DIR/etc
VERSION_FILE=$SCRIPT_DIR_ETC/version
DOMAIN_FILE=$SCRIPT_DIR_ETC/domain
INSTALLATION_DIR=/usr/local/lib

PHP_NAME=php
PHP_VERSION=$(cat $VERSION_FILE)
PHP_FULL_NAME=$PHP_NAME-$PHP_VERSION

DIR=$INSTALLATION_DIR/$PHP_NAME$PHP_VERSION
DIR_SRC=$DIR/src

PHP_DIR=$DIR_SRC/$PHP_FULL_NAME
PHP_ARCHIVE_TYPE=tar.bz2
PHP_ARCHIVE_NAME=$PHP_FULL_NAME.$PHP_ARCHIVE_TYPE

DOWNLOAD_HOST=$(cat $DOMAIN_FILE)
DOWNLOAD_URL="http://$DOWNLOAD_HOST/distributions/$PHP_ARCHIVE_NAME"

PREFIX=$DIR
EPREFIX=$PREFIX

PHP=$EPREFIX/bin/php
PHPFPM=$EPREFIX/sbin/php-fpm

PECL=$EPREFIX/bin/pecl
PEAR=$EPREFIX/bin/pear
PHPIZE=$EPREFIX/bin/phpize
PHPCONFIG=$EPREFIX/bin/php-config

PHP_INI_DIR=$PREFIX/etc
EXTENSION_INI_DIR=$PHP_INI_DIR/php
if [ -f "$PHPCONFIG" ]; then
  EXTENSION_DIR=$($PHPCONFIG --extension-dir)
fi

if [ -f "$PEAR" ]; then
  PEAR_DOWNLOAD_DIR=$($PEAR config-get download_dir)
fi

function check_php_extension() {
  if [ -f $EXTENSION_PATH_TO_INI ] ; then
    echo "The '$EXTENSION_NAME' PHP extension is already installed in PHP $PHP_VERSION"
    echo -n "Reinstall '$EXTENSION_NAME' extension? (yes/[no]): "
    while read INPUTTED_CONFIRMATION
    do
      if [ "$INPUTTED_CONFIRMATION" = "yes" ] ; then
        echo -n "Started to delete '$EXTENSION_NAME' extension for PHP $PHP_VERSION ... "
        rm $EXTENSION_PATH_TO_INI || echo "[ Error ]" && echo "[ OK ]"

        if [ -f $EXTENSION_PATH_TO_SO ] ; then
          rm $EXTENSION_PATH_TO_SO
        fi;
      else
        echo "Cancel installation '$EXTENSION_NAME' extension for PHP $PHP_VERSION ... [ OK ]"
        exit 0
      fi
      break
    done
  fi;

  if [ ! -d $EXTENSION_INI_DIR ] ; then
    mkdir -p $EXTENSION_INI_DIR
  fi;
}

function create_symlink_to() {
  SYMLINK_NAME=$1
  SYMLINK_FROM=$2
  SYMLINK_TO=$3
  SYMLINK=$SYMLINK_FROM/$SYMLINK_NAME

  echo " "
  echo "Trying to create symlink '$SYMLINK' in $SYMLINK_TO";
  echo "-----"

  if [ -e $SYMLINK ] ; then
    if [ -d $SYMLINK_TO ] ; then
      echo -n " Trying to change current directory to: '$SYMLINK_TO' ... "
      cd $SYMLINK_TO || echo "[ Error ]" && echo "[ OK ]"

      if [ "$(pwd)" = "$SYMLINK_TO" ] ; then
        if [ -L $SYMLINK_NAME ] || [ -e $SYMLINK_NAME ] ; then
          echo -n " Trying to delete '$SYMLINK_NAME' ... "
          sudo rm $SYMLINK_NAME || echo "[ Error ]" && echo "[ OK ]"
        fi

        echo -n " Trying to create symlink to: '$SYMLINK' ... "
        sudo ln -s $SYMLINK || echo "[ Error ]" && echo "[ OK ]"
      else
        echo  " [ Error ] Can't change current directory to: '$SYMLINK_TO'"
      fi

    else
      echo  " [ Error ] Can't find directory: '$SYMLINK_TO'"
    fi
  else
    echo  " [ Error ] '$SYMLINK' doesn't exist"
  fi

  echo " "
}

