#!/usr/bin/env bash

NAME=$(basename $0)
SCRIPT=$(readlink -f $0)
SCRIPT_DIR=$(dirname $SCRIPT)
. $SCRIPT_DIR/environment

install_http() {
  $SCRIPT_DIR/install-http
}

install_pcntl() {
  $SCRIPT_DIR/install-pcntl
}

show_help() {
  echo "------------------------------------------------"
  echo " Script for easy installation of PHP extension. "
  echo "------------------------------------------------"
  echo "Author:   $AUTHOR"
  echo "Version:  $VERSION"
  echo ""
  echo "Commands:"
  echo "  http       - installation of pecl_http extension (http://www.php.net/manual/en/book.http.php)"
  echo "  pcntl      - installation of pcntl extension (http://www.php.net/manual/en/book.pcntl.php)"
  echo "  help       - show this message"
}

case "$1" in
  http)
    install_http
  ;;
  pcntl)
    install_pcntl
  ;;
  help)
    show_help
  ;;
  *)
    echo "Usage: $NAME {http|pcntl|help}"
  ;;
esac
