#!/usr/bin/env bash

show_installed_extensions() {
  echo "List of installed extensions for PHP $PHP_VERSION:"
  find $EXTENSION_DIR -iname '*.so' -type f
  echo "List of enabled extensions for PHP $PHP_VERSION:"
  cat $EXTENSION_INI_DIR/*
}

install_extension_pcntl() { # {{{
  install_php_source_extension pcntl $PCNLT_CUSTOM_VERSION
} # }}}

install_extension_pthreads() { # {{{
  install_php_pecl_extension pthreads $PTHREADS_CUSTOM_VERSION
} # }}}

install_extension_raphf() { # {{{
  install_php_pecl_extension raphf $RAPHF_CUSTOM_VERSION
} # }}}

install_extension_propro() { # {{{
  install_php_pecl_extension propro $PROPRO_CUSTOM_VERSION
} # }}}

install_extension_http() { # {{{
  install_php_pecl_extension http $HTTP_CUSTOM_VERSION
} # }}}

install_extension_gearman() { # {{{
  install_php_pecl_extension gearman $GEARMAN_CUSTOM_VERSION
} # }}}

install_extension_memcached() { # {{{
  install_php_pecl_extension memcached $MEMCACHED_CUSTOM_VERSION
} # }}}

install_extension_imagick() { # {{{
  install_php_pecl_extension imagick $IMAGICK_CUSTOM_VERSION
} # }}}

install_extension_couchbase() { # {{{
  install_php_pecl_extension couchbase $COUCHBASE_CUSTOM_VERSION
} # }}}

install_extension_cassandra() { # {{{
  install_php_pecl_extension cassandra $CASSANDRA_CUSTOM_VERSION
} # }}}

install_extension_redis() { # {{{
  install_php_pecl_extension redis $redis_CUSTOM_VERSION
}

install_extension_xdebug() { # {{{
  install_php_pecl_extension xdebug $XDEBUG_CUSTOM_VERSION

#  +----------------------------------------------------------------------+
#  |   /etc/php5/conf.d/xdebug.ini                                        |
#  |   ===========================                                        |
#  |                                                                      |
#  |   ; point this to wherever your xdebug.so is located                 |
#  |   zend_extension=/usr/lib/php5/20090626/xdebug.so                    |
#  |   xdebug.remote_enable=1                                             |
#  |   xdebug.remote_host=localhost                                       |
#  |   xdebug.remote_port=9000                                            |
#  |                                                                      |
#  |   xdebug.remote_autostart=1                                          |
#  +----------------------------------------------------------------------+


#  +----------------------------------------------------------------------+
#  |                                                                      |
#  |   INSTALLATION INSTRUCTIONS                                          |
#  |   =========================                                          |
#  |                                                                      |
#  |   See http://xdebug.org/install.php#configure-php for instructions   |
#  |   on how to enable Xdebug for PHP.                                   |
#  |                                                                      |
#  |   Documentation is available online as well:                         |
#  |   - A list of all settings:  http://xdebug.org/docs-settings.php     |
#  |   - A list of all functions: http://xdebug.org/docs-functions.php    |
#  |   - Profiling instructions:  http://xdebug.org/docs-profiling2.php   |
#  |   - Remote debugging:        http://xdebug.org/docs-debugger.php     |
#  |                                                                      |
#  |                                                                      |
#  |   NOTE: Please disregard the message                                 |
#  |       You should add "extension=xdebug.so" to php.ini                |
#  |   that is emitted by the PECL installer. This does not work for      |
#  |   Xdebug.                                                            |
#  |                                                                      |
#  +----------------------------------------------------------------------+

} # }}}

show_help() { # {{{
  if [ -x "$(which display-im6)" ] && [ ${SCRIPT_OPTIONS["imagick"]} == true ]; then
    IMAGE_MAGICK_INFO=$(display-im6 -version | grep Version)

    IMAGE_MAGICK_NAME=$(echo ${IMAGE_MAGICK_INFO} | awk {'print $2'})
    IMAGE_MAGICK_VERSION=$(echo ${IMAGE_MAGICK_INFO} | awk {'print $3'} | sed '/\-/s/\-.*//g')
    IMAGE_MAGICK_BIN_PREFIX=$(echo ${IMAGE_MAGICK_INFO} | awk {'print $4'})
    IMAGE_MAGICK_ARCHITECTURE=$(echo ${IMAGE_MAGICK_INFO} | awk {'print $5'})

    echo "------------------------------------------------------------------------------------------------------------------------"
    echo " ${IMAGE_MAGICK_NAME} (${IMAGE_MAGICK_VERSION}):"
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo "  sudo apt-get install imagemagick imagemagick-common libmagickwand-dev imagemagick-doc"
    echo "  cd /usr/bin"
    echo "  sudo ln -s /usr/lib/${IMAGE_MAGICK_ARCHITECTURE}-linux-gnu/${IMAGE_MAGICK_NAME}-${IMAGE_MAGICK_VERSION}/bin-${IMAGE_MAGICK_BIN_PREFIX}/Wand-config"
    echo "  sudo ln -s /usr/lib/${IMAGE_MAGICK_ARCHITECTURE}-linux-gnu/${IMAGE_MAGICK_NAME}-${IMAGE_MAGICK_VERSION}/bin-${IMAGE_MAGICK_BIN_PREFIX}/Magick-config"
    echo "  sudo ln -s /usr/lib/${IMAGE_MAGICK_ARCHITECTURE}-linux-gnu/${IMAGE_MAGICK_NAME}-${IMAGE_MAGICK_VERSION}/bin-${IMAGE_MAGICK_BIN_PREFIX}/MagickWand-config"
    echo "------------------------------------------------------------------------------------------------------------------------"
  elif [ ${SCRIPT_OPTIONS["cassandra"]} == true ]; then
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo " DataStax C/C++ Driver for Apache Cassandra: http://datastax.github.io/cpp-driver/ "
    echo "  Code: https://github.com/datastax/cpp-driver "
    echo "  Binaries: http://downloads.datastax.com/cpp-driver/ubuntu/14.04/ "
    echo "    -- libuv_1.7.5-1_amd64.deb"
    echo "    -- libuv-dev_1.7.5-1_amd64.deb"
    echo "    -- cassandra-cpp-driver_2.1.0-1_amd64.deb"
    echo "    -- cassandra-cpp-driver-dev_2.1.0-1_amd64.deb"
    echo "  Docs: http://datastax.github.io/cpp-driver/ "
    echo "------------------------------------------------------------------------------------------------------------------------"
  else
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo " Script for easy installation of PHP extension. "
    echo "------------------------------------------------------------------------------------------------------------------------"
    echo "Author:   $AUTHOR"
    echo "Version:  $VERSION"
    echo ""
    echo "Commands:"
    echo "  list       - list of instaled PHP extension"
    echo "  raphf      - installation of raphf extension (http://pecl.php.net/package/raphf)"
    echo "  propro     - installation of propro extension (http://pecl.php.net/package/propro)"
    echo "  http       - installation of pecl_http extension (http://www.php.net/manual/en/book.http.php)"
    echo "  pcntl      - installation of pcntl extension (http://www.php.net/manual/en/book.pcntl.php)"
    echo "  couchbase  - installation of couchbase extension (http://www.couchbase.com/communities/php/getting-started), Detail: http://www.couchbase.com/communities/c-client-library"
    echo "  cassandra  - installation of cassandra extension (http://datastax.github.io/php-driver/)"
    echo "  redis      - installation of redis extension (https://pecl.php.net/package/redis)"
    echo "  memcached  - installation of memcached extension (http://ua2.php.net/manual/ru/book.memcached.php)"
    echo "  gearman    - installation of gearman extension (http://ua2.php.net/manual/ru/book.gearman.php)"
    echo "  imagick    - installation of imagick extension (http://pecl.php.net/package/imagick)"
    echo "  help       - show this message"
    echo ""
    echo "Extended help about installation and configuration of imagick|cassandra extension:"
    echo "  php-installer extension help --imagick"
    echo "  php-installer extension help --cassandra"
    echo "------------------------------------------------------------------------------------------------------------------------"
  fi
} # }}}

case "$SCRIPT_SUB_ACTION" in
  list)
    show_installed_extensions
  ;;
  pcntl)
    install_extension_pcntl
  ;;
  pthreads)
    install_extension_pthreads
  ;;
  http)
    install_extension_http
  ;;
  gearman)
    install_extension_gearman
  ;;
  memcached)
    install_extension_memcached
  ;;
  couchbase)
    install_extension_couchbase
  ;;
  cassandra)
    install_extension_cassandra
  ;;
  redis)
    install_extension_redis
  ;;
  xdebug)
    install_extension_xdebug
  ;;
  raphf)
    install_extension_raphf
  ;;
  propro)
    install_extension_propro
  ;;
  imagick)
    install_extension_imagick
  ;;
  help)
    show_help
  ;;
  *)
    echo "Usage: $NAME {list|pcntl|pthreads|http|gearman|memcached|couchbase|cassandra|redis|xdebug|raphf|propro|imagick|help}"
  ;;
esac
