#!/usr/bin/env bash

NAME=$(basename $0)
SCRIPT=$(readlink -f $0)
SCRIPT_DIR=$(dirname $SCRIPT)
. $SCRIPT_DIR/environment

if [ ! -d $DIR_SRC ] ; then
  mkdir -p $DIR_SRC
fi

cd $DIR_SRC
if [ ! -f $DIR_SRC/$PHP_ARCHIVE_NAME ] ; then
  $WGET_COMMAND $DOWNLOAD_URL
fi

if [ ! -d $PHP_DIR ] ; then
  $TAR_COMMAND -xvf $PHP_ARCHIVE_NAME
fi

cd $PHP_DIR

./configure --prefix=$PREFIX \
            --exec-prefix=$EPREFIX \
            --with-config-file-scan-dir=$EXTENSION_INI_DIR \
            --disable-ipv6 \
            --with-mhash \
            --enable-shmop \
            --enable-sockets \
            --with-openssl \
            --with-curl \
            --enable-soap \
            --enable-libxml \
            --with-xsl \
            --enable-zip \
            --with-zlib \
            --enable-ftp \
            --enable-fpm \
            --with-mysql=mysqlnd \
            --with-mysqli=mysqlnd \
            --with-pdo-mysql=mysqlnd \
            --enable-calendar \
            --enable-mbstring \
            --enable-intl \
            --with-gd \
            --enable-gd-native-ttf \
            --enable-gd-jis-conv \
            --with-jpeg-dir \
            --with-png-dir \
            --with-freetype-dir \
            --enable-exif \
            --with-layout=GNU \
            --with-regex=php \
            --enable-maintainer-zts \
            --with-zend-vm=CALL

# install
make install

# copy ini file
cp $SCRIPT_DIR_ETC/php/php.ini $PHP_INI_DIR/

# copy fpm configuration file
cp $SCRIPT_DIR_ETC/php/php-fpm.conf $PHP_INI_DIR/

