#!/usr/bin/env bash

NAME=$(basename $0)
SCRIPT=$(realpath $0)
SCRIPT_DIR=$(dirname $SCRIPT)
cd $SCRIPT_DIR || exit 1 && echo "Change current directory to '$SCRIPT_DIR'."

. $SCRIPT_DIR/environment

EXTENSION_NAME=gearman
EXTENSION_VERSION=1.1.2
EXTENSION_DOWNLOAD_NAME=$EXTENSION_NAME

EXTENSION_FULL_NAME=$EXTENSION_DOWNLOAD_NAME-$EXTENSION_VERSION
EXTENSION_SOURCE=$DIR_SRC/$EXTENSION_FULL_NAME
EXTENSION_ARCHIVE=$EXTENSION_SOURCE.tgz

EXTENSION_SO=$EXTENSION_NAME.so
EXTENSION_PATH_TO_SO=$EXTENSION_DIR/$EXTENSION_SO

EXTENSION_INI=$EXTENSION_NAME.ini
EXTENSION_PATH_TO_INI=$EXTENSION_INI_DIR/$EXTENSION_INI

check_php_extension

cd $DIR_SRC && echo "Change current directory to '$DIR_SRC'" || exit 1

echo "Try to downloaded: '$EXTENSION_DOWNLOAD_NAME'"
$PECL download $EXTENSION_DOWNLOAD_NAME || exit 1

if [ -f $DIR_SRC/channel.xml ] ; then
  rm $DIR_SRC/channel.xml
fi;

echo "Start unzip: '$EXTENSION_ARCHIVE'"
gzip -d < $EXTENSION_ARCHIVE | tar -xvf -

if [ -f $DIR_SRC/package.xml ] ; then
  rm $DIR_SRC/package.xml
fi;

cd $EXTENSION_SOURCE || exit 1 && echo "Change current directory to '$EXTENSION_SOURCE'."

$PHPIZE || exit 1

# configure
./configure --prefix=$PREFIX --exec-prefix=$EPREFIX --with-$EXTENSION_NAME --enable-shared=PKGS --with-php-config=$PHPCONFIG || exit 1

# install
make install || exit 1

echo "extension=$EXTENSION_SO" > $EXTENSION_PATH_TO_INI && echo "Save 'extension=$EXTENSION_SO' to '$EXTENSION_PATH_TO_INI'."

