#!/usr/bin/env bash

if [ ! -d $DIR_SRC ] ; then
  mkdir -p $DIR_SRC || exit 1
fi

cd $DIR_SRC || exit 2
if [ ! -f $DIR_SRC/$PHP_ARCHIVE_NAME ] ; then
  wget $DOWNLOAD_URL || exit 3
fi

if [ ! -d $PHP_DIR ] ; then
  tar -xvf $PHP_ARCHIVE_NAME || exit 4
fi

cd $PHP_DIR || exit 5

./configure --prefix=$PREFIX \
            --exec-prefix=$EPREFIX \
            --with-config-file-scan-dir=$EXTENSION_INI_DIR \
            --disable-ipv6 \
            --enable-zip \
            --enable-ftp \
            --enable-fpm \
            --enable-intl \
            --enable-exif \
            --enable-soap \
            --enable-shmop \
            --enable-libxml \
            --enable-sockets \
            --enable-calendar \
            --enable-mbstring \
            --enable-maintainer-zts \
            --with-xsl \
            --with-curl \
            --with-zlib \
            --with-mhash \
            --with-openssl \
            --with-mysql=mysqlnd \
            --with-mysqli=mysqlnd \
            --with-pdo-mysql=mysqlnd \
            --with-gd \
            --enable-gd-native-ttf \
            --enable-gd-jis-conv \
            --with-freetype-dir \
            --with-jpeg-dir \
            --with-png-dir \
            --with-vpx-dir \
            --with-xmp-dir \
            --with-layout=GNU \
            --with-regex=php \
            --with-zend-vm=CALL \
          || exit 6

# install
make install || exit 7

