#!/usr/bin/env bash

NAME=$(basename $0)
SCRIPT=$(realpath $0)
SCRIPT_DIR=$(dirname $SCRIPT)
cd $SCRIPT_DIR || exit 1 && echo "Change current directory to '$SCRIPT_DIR'"

. $SCRIPT_DIR/environment

PHP_PCNTL_DIR=$PHP_DIR/ext/pcntl/
EXTENSION_NAME=pcntl
EXTENSION_PATH_TO_SO=$EXTENSION_DIR/$EXTENSION_NAME.so
EXTENSION_PATH_TO_INI=$EXTENSION_INI_DIR/$EXTENSION_NAME.ini

check_php_extension

cd $PHP_PCNTL_DIR || exit 1 && echo "Change current directory to '$PHP_PCNTL_DIR'"

$PHPIZE || exit 1

# configure
./configure --prefix=$PREFIX --exec-prefix=$EPREFIX --enable-$EXTENSION_NAME --enable-shared=PKGS --with-php-config=$PHPCONFIG || exit 1

# install
make install || exit 1

echo "extension=$EXTENSION_NAME.so" > $EXTENSION_PATH_TO_INI && echo "Save 'extension=$EXTENSION_NAME.so' to '$EXTENSION_PATH_TO_INI'"

