#!/usr/bin/env bash

NAME=$(basename $0)
SCRIPT=$(realpath $0)
SCRIPT_DIR=$(dirname $SCRIPT)
cd $SCRIPT_DIR || exit 1 && echo "Change current directory to '$SCRIPT_DIR'"

. $SCRIPT_DIR/environment

install_php_pecl_extension xdebug 2.2.3 zend_extension

#  +----------------------------------------------------------------------+
#  |   /etc/php5/conf.d/xdebug.ini                                        |
#  |   ===========================                                        |
#  |                                                                      |
#  |   ; point this to wherever your xdebug.so is located                 |
#  |   zend_extension=/usr/lib/php5/20090626/xdebug.so                    |
#  |   xdebug.remote_enable=1                                             |
#  |   xdebug.remote_host=localhost                                       |
#  |   xdebug.remote_port=9000                                            |
#  |                                                                      |
#  |   xdebug.remote_autostart=1                                          |
#  +----------------------------------------------------------------------+


#  +----------------------------------------------------------------------+
#  |                                                                      |
#  |   INSTALLATION INSTRUCTIONS                                          |
#  |   =========================                                          |
#  |                                                                      |
#  |   See http://xdebug.org/install.php#configure-php for instructions   |
#  |   on how to enable Xdebug for PHP.                                   |
#  |                                                                      |
#  |   Documentation is available online as well:                         |
#  |   - A list of all settings:  http://xdebug.org/docs-settings.php     |
#  |   - A list of all functions: http://xdebug.org/docs-functions.php    |
#  |   - Profiling instructions:  http://xdebug.org/docs-profiling2.php   |
#  |   - Remote debugging:        http://xdebug.org/docs-debugger.php     |
#  |                                                                      |
#  |                                                                      |
#  |   NOTE: Please disregard the message                                 |
#  |       You should add "extension=xdebug.so" to php.ini                |
#  |   that is emitted by the PECL installer. This does not work for      |
#  |   Xdebug.                                                            |
#  |                                                                      |
#  +----------------------------------------------------------------------+

