#!/usr/bin/env bash

NAME=$(basename $0)
SCRIPT=$(realpath $0)
SCRIPT_DIR=$(dirname $SCRIPT)
cd $SCRIPT_DIR || exit 1 && echo "Change current directory to '$SCRIPT_DIR'"

. $SCRIPT_DIR/environment

install_php_pecl_extension "http" "2.0.4" "extension" "pecl_http"

