#!/usr/bin/env bash

NAME=$(basename $0)
SCRIPT=$(readlink -f $0)
SCRIPT_DIR=$(dirname $SCRIPT)
cd $SCRIPT_DIR

. $SCRIPT_DIR/environment

EXTENSION_NAME=http
EXTENSION_VERSION=1.7.5
EXTENSION_DOWNLOAD_NAME=pecl_http

EXTENSION_FULL_NAME=$EXTENSION_DOWNLOAD_NAME-$EXTENSION_VERSION
EXTENSION_SOURCE=$DIR_SRC/$EXTENSION_FULL_NAME
EXTENSION_ARCHIVE=$EXTENSION_SOURCE.tgz

EXTENSION_SO=$EXTENSION_NAME.so
EXTENSION_PATH_TO_SO=$EXTENSION_DIR/$EXTENSION_SO

EXTENSION_INI=$EXTENSION_NAME.ini
EXTENSION_PATH_TO_INI=$EXTENSION_INI_DIR/$EXTENSION_INI

if [ ! -d $EXTENSION_INI_DIR ] ; then
  mkdir -p $EXTENSION_INI_DIR
fi;

if [ -f $EXTENSION_PATH_TO_SO ] ; then
  rm $EXTENSION_PATH_TO_SO
fi;

cd $DIR_SRC
$PECL download $EXTENSION_DOWNLOAD_NAME
echo "Downloaded: '$EXTENSION_DOWNLOAD_NAME'"

if [ -f $DIR_SRC/channel.xml ] ; then
  rm $DIR_SRC/channel.xml
fi;

echo "Start unzip: '$EXTENSION_ARCHIVE'."
gzip -d < $EXTENSION_ARCHIVE | tar -xvf -

if [ -f $DIR_SRC/package.xml ] ; then
  rm $DIR_SRC/package.xml
fi;

cd $EXTENSION_SOURCE
echo "Change current directory to '$EXTENSION_SOURCE'."

$PHPIZE

# configure
./configure --prefix=$PREFIX --exec-prefix=$EPREFIX --enable-$EXTENSION_NAME --enable-shared=PKGS --with-php-config=$PHPCONFIG

# install
make install

# configure
echo "extension=$EXTENSION_SO" > $EXTENSION_PATH_TO_INI
echo "Save 'extension=$EXTENSION_SO' to '$EXTENSION_PATH_TO_INI'."

