#!/usr/bin/env bash

NAME=$(basename $0)
SCRIPT=$(readlink -f $0)
SCRIPT_DIR=$(dirname $SCRIPT)
cd $SCRIPT_DIR || exit 1 && echo "Change current directory to '$SCRIPT_DIR'"

. $SCRIPT_DIR/environment

EXTENSION_NAME=http
EXTENSION_VERSION=1.7.5
EXTENSION_DOWNLOAD_NAME=pecl_http

EXTENSION_FULL_NAME=$EXTENSION_DOWNLOAD_NAME-$EXTENSION_VERSION
EXTENSION_SOURCE=$DIR_SRC/$EXTENSION_FULL_NAME
EXTENSION_ARCHIVE=$EXTENSION_SOURCE.tgz

EXTENSION_SO=$EXTENSION_NAME.so
EXTENSION_PATH_TO_SO=$EXTENSION_DIR/$EXTENSION_SO

EXTENSION_INI=$EXTENSION_NAME.ini
EXTENSION_PATH_TO_INI=$EXTENSION_INI_DIR/$EXTENSION_INI

if [ -f $EXTENSION_PATH_TO_INI ] ; then
  echo "The '$EXTENSION_NAME' PHP extension is already installed in PHP $PHP_VERSION"
  echo -n "Reinstall '$EXTENSION_NAME' extension? (yes/[no]): "
  while read INPUTTED_CONFIRMATION
  do
    if [ "$INPUTTED_CONFIRMATION" = "yes" ] ; then
      echo -n "Started to delete '$EXTENSION_NAME' extension for PHP $PHP_VERSION ... "
      rm $EXTENSION_PATH_TO_INI || echo "[ Error ]" && echo "[ OK ]"
    else
      echo "Cancel installation '$EXTENSION_NAME' extension for PHP $PHP_VERSION ... [ OK ]"
      exit 0
    fi
    break
  done
fi;

if [ ! -d $EXTENSION_INI_DIR ] ; then
  mkdir -p $EXTENSION_INI_DIR
fi;

if [ -f $EXTENSION_PATH_TO_SO ] ; then
  rm $EXTENSION_PATH_TO_SO
fi;

cd $DIR_SRC && echo "Change current directory to '$DIR_SRC'" || exit 1

echo "Try to downloaded: '$EXTENSION_DOWNLOAD_NAME'"
$PECL download $EXTENSION_DOWNLOAD_NAME || exit 1

if [ -f $DIR_SRC/channel.xml ] ; then
  rm $DIR_SRC/channel.xml
fi;

echo "Start unzip: '$EXTENSION_ARCHIVE'"
gzip -d < $EXTENSION_ARCHIVE | tar -xvf -

if [ -f $DIR_SRC/package.xml ] ; then
  rm $DIR_SRC/package.xml
fi;

cd $EXTENSION_SOURCE || exit 1 && echo "Change current directory to '$EXTENSION_SOURCE'"

$PHPIZE || exit 1

# configure
./configure --prefix=$PREFIX --exec-prefix=$EPREFIX --enable-$EXTENSION_NAME --enable-shared=PKGS --with-php-config=$PHPCONFIG || exit 1

# install
make install || exit 1 

# configure
echo "extension=$EXTENSION_SO" > $EXTENSION_PATH_TO_INI && echo "Save 'extension=$EXTENSION_SO' to '$EXTENSION_PATH_TO_INI'"

