#!/usr/bin/env bash

OS=$(uname)
SUDO=$(which sudo)
APT_GET=$(which apt-get)

# Execute from root {{{
if [ "$USER" = "root" ] ; then
  EXECUTE_FROM_ROOT=""
elif [ -x "$SUDO" ] ; then
  EXECUTE_FROM_ROOT="sudo"
else
  EXECUTE_FROM_ROOT="su -c"
fi
# }}}

function command_exists() { # {{{
  COMMAND_NAME=$1
  COMMAND_PATH=$(which $COMMAND_NAME)

  if [ ! -x "$COMMAND_PATH" ]; then
    echo "$COMMAND_NAME: command not found in your $OS system"

    if [ -x "$APT_GET" ]; then
      echo " - try execute: $EXECUTE_FROM_ROOT apt-get install $COMMAND_NAME"
    fi
    exit 1
  fi
} # }}}

# Check commands {{{
  command_exists ls
  command_exists cp
  command_exists ps
  command_exists tr
  command_exists wc
  command_exists cat
  command_exists awk
  command_exists tar
  command_exists sed
  command_exists wget
  command_exists find
  command_exists grep
  command_exists make
  command_exists mkdir
  command_exists touch
  command_exists dirname
  command_exists basename
  command_exists realpath
# }}}

NAME=$(basename $0)
SCRIPT=$(realpath $0)
SCRIPT_DIR=$(dirname $SCRIPT)

SCRIPT_ACTION=$1
SCRIPT_SUB_ACTION=$2

. $SCRIPT_DIR/environment

show_installed() { # {{{
  echo "List of installed PHP versions:"
  find $INSTALLATION_DIR/* -iname "$PHP_NAME*" -type d -prune
} # }}}

show_version() { # {{{
  echo "PHP Version: $PHP_VERSION"
} # }}}

change_version() { # {{{
  echo -n "Enter PHP version [$PHP_VERSION]: "
  while read INPUTTED_VERSION
  do
    if [[ "$INPUTTED_VERSION" =~ ^[0-9]+(\.[0-9]+){1,2}$ ]] ; then 
      echo -n "Change PHP version to $INPUTTED_VERSION ... "
      echo $INPUTTED_VERSION > $VERSION_FILE || echo "[ Error ]" && echo "[ OK ]"
      break
    else
      echo "Incorrect format '$INPUTTED_VERSION' (correct example: 5.4.25)"
      exit 1
    fi
  done
} # }}}

update_php() { # {{{
  . $SCRIPT_DIR/update
} # }}}

configure_php() { # {{{
  . $SCRIPT_DIR/configure
} # }}}

install_php() { # {{{
  . $SCRIPT_DIR/install
} # }}}

install_extension() { # {{{
  . $SCRIPT_DIR/extension
} # }}}

delete_php() { # {{{
  . $SCRIPT_DIR/delete
} # }}}

setup_php() { # {{{
  . $SCRIPT_DIR/setup
} # }}}

show_help() { # {{{
  echo "-------------------------------------------------------"
  echo " Script for easy installation more one version of PHP. "
  echo "-------------------------------------------------------"
  echo "Author:   $AUTHOR"
  echo "Version:  $VERSION"
  echo ""
  echo "Commands:"
  echo "  list       - show list of installed versions of PHP"
  echo "  show       - show used version of PHP"
  echo "  change     - change used version of PHP"
  echo "  install    - installation of selected version of PHP"
  echo "  extension  - show menu for work with extensions of PHP"
  echo "  configure  - create configuration files of PHP"
  echo "  delete     - delete of selected version of PHP"
  echo "  setup      - setup needed package for PHP compilation"
  echo "  help       - show this message"
} # }}}

case "$SCRIPT_ACTION" in
  list)
    show_installed
  ;;
  show)
    show_version
  ;;
  change)
    change_version
  ;;
  update)
    update_php
  ;;
  install)
    install_php
  ;;
  extension)
    install_extension
  ;;
  configure)
    configure_php
  ;;
  delete)
    delete_php
  ;;
  setup)
    setup_php
  ;;
  help)
    show_help
  ;;
  *)
    echo "Usage: $NAME {list|show|change|update|install|extension|configure|delete|setup|help}"
  ;;
esac
