#!/usr/bin/env bash

if [ -x $APT_GET ] ; then
  $EXECUTE_FROM_ROOT apt-get install wget tar unzip gzip bzip2 realpath \
                                     re2c g++ pkg-config curl \
                                     libcurl4-gnutls-dev libssl-dev libxml2-dev libxslt1-dev \
                                     libfreetype6-dev libghc-text-icu-dev libicu-dev \
                                     libjpeg8-dev libpng++-dev \
                                     libmemcached-dev libgearman-dev \
                                     libvpx-dev libvpx-doc libvpx1 \
                                     libxpm-dev xpmutils libxpm4 autoconf
fi

