#!/usr/bin/env bash

################################################################################
# SUDO
################################################################################
$EXECUTE_FROM_ROOT echo "Start modification with root privileges" || exit 1

PHP_FPM_PID=$(ps ax | grep  php-fpm:.*$DIR | grep -v grep | awk '{print $1}')
if [ $PHP_FPM_PID > 0 ] ; then
  echo "Found started php-fpm: $PHP_FPM_PID ($DIR)"
else
  $EXECUTE_FROM_ROOT $DIR/sbin/php-fpm
fi

################################################################################
# PHP: default socket
################################################################################

#create_symlink_to "php5-fpm.sock" "$DIR/var/run" "/var/run"

################################################################################
# Nginx configuration: Add upstream 
################################################################################

#create_symlink_to "upstream.conf" "$SCRIPT_DIR/etc/nginx" "/etc/nginx/conf.d"

