#!/usr/bin/env bash

NAME=$(basename $0)
SCRIPT=$(readlink -f $0)
SCRIPT_DIR=$(dirname $SCRIPT)
cd $SCRIPT_DIR

. $SCRIPT_DIR/environment

################################################################################
# /usr/local/bin
################################################################################
create_symlink_to "peardev" "$DIR/bin" "/usr/local/bin"
create_symlink_to "pecl" "$DIR/bin" "/usr/local/bin"
create_symlink_to "phar" "$DIR/bin" "/usr/local/bin"
create_symlink_to "php" "$DIR/bin" "/usr/local/bin"
create_symlink_to "php-cgi" "$DIR/bin" "/usr/local/bin"
create_symlink_to "php-config" "$DIR/bin" "/usr/local/bin"
create_symlink_to "phpize" "$DIR/bin" "/usr/local/bin"

################################################################################
# /usr/local/sbin
################################################################################
create_symlink_to "php-fpm" "$DIR/sbin" "/usr/local/sbin"

################################################################################
# SUDO
################################################################################
sudo echo "Start modification with root privileges" || exit 1

################################################################################
# PHP: default socket
################################################################################

create_symlink_to "php5-fpm.sock" "$DIR/var/run" "/var/run"

################################################################################
# Nginx configuration: Add upstream 
################################################################################

create_symlink_to "upstream.conf" "$SCRIPT_DIR/etc/nginx" "/etc/nginx/conf.d"

